"""E2E: recordings serialized BEFORE the (owner, name) identity refactor
still play back correctly.

``assets/pre_scope_recording.viser`` was generated by actual pre-refactor
code (the branch's merge-base) -- its messages carry no ``owner`` /
``virtual`` stamps, so this pins the deserialization defaults and the
client-side parent-anchor fallback for the old format end to end.
"""

from __future__ import annotations

import functools
import http.server
import threading
from pathlib import Path

from playwright.sync_api import Page

import viser

from .utils import find_free_port, wait_for_scene_node, wait_for_scene_node_hidden

_ASSETS = Path(__file__).parent / "assets"


class _CORSHandler(http.server.SimpleHTTPRequestHandler):
    """The recording is served from a different origin than the viewer."""

    def end_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()

    def log_message(self, *args) -> None:
        pass  # Keep pytest output clean.


def test_pre_scope_recording_plays_back(
    viser_server: viser.ViserServer, page: Page
) -> None:
    file_port = find_free_port()
    httpd = http.server.ThreadingHTTPServer(
        ("127.0.0.1", file_port),
        functools.partial(_CORSHandler, directory=str(_ASSETS)),
    )
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    try:
        page.goto(
            f"http://localhost:{viser_server.get_port()}/"
            f"?playbackPath=http://127.0.0.1:{file_port}/pre_scope_recording.viser"
        )

        # Every node from the old recording, including the auto-created
        # ancestors of the deep add (the old format has no server-sent
        # virtual anchors; the client-side makeParents fallback covers it).
        for name in (
            "/root_frame",
            "/root_frame/box",
            "/root_frame/box/label",
            "/lines",
            "/hidden_box",
            "/deep",
            "/deep/nested",
            "/deep/nested/sphere",
        ):
            wait_for_scene_node(page, name, timeout=15_000)

        # Un-stamped messages must resolve to the broadcast scope.
        owners = page.evaluate(
            """() => {
                const state = window.__viserSceneTree.getState();
                return ["/root_frame", "/lines", "/deep/nested/sphere"].map(
                    (n) => state[n].message.owner ?? "",
                );
            }"""
        )
        assert owners == ["", "", ""]

        # Recorded poses and visibility land.
        page.wait_for_function(
            """() => {
                const pose =
                    window.__viserMutable?.nodePoseData?.["/root_frame"];
                return pose && Math.abs(pose.position[0] - 0.5) < 1e-4;
            }""",
            timeout=15_000,
        )
        wait_for_scene_node_hidden(page, "/hidden_box", timeout=15_000)
    finally:
        httpd.shutdown()
