"""Verify that every public ``viser`` export is referenced in the API docs.

Catches the common drift where a new handle, event, or type alias gets exported
from ``viser/__init__.py`` but never makes it into ``docs/source/**/*.rst``.
"""

import re
from pathlib import Path

import viser

REPO_ROOT = Path(__file__).parent.parent
DOCS_API_DIR = REPO_ROOT / "docs" / "source" / "api"

# Matches Sphinx auto-directives that pull in a ``viser.X`` symbol:
#   .. autoclass:: viser.Foo
#   .. autoclass:: viser.Foo()
#   .. autoclass:: viser.infra.StateSerializer  (captures "infra")
#   .. autodata:: viser.BAR
#   .. autofunction:: viser.baz
#   .. automodule:: viser.theme
DIRECTIVE_RE = re.compile(
    r"^\s*\.\.\s+(?:autoclass|autodata|autofunction|automodule)::\s+viser\.([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)


def test_all_public_exports_documented() -> None:
    public = {name for name in dir(viser) if not name.startswith("_")}

    documented: set[str] = set()
    for rst_path in DOCS_API_DIR.rglob("*.rst"):
        documented.update(DIRECTIVE_RE.findall(rst_path.read_text()))

    missing = sorted(public - documented)
    assert not missing, (
        "The following public viser exports are not referenced via "
        "autoclass/autodata/autofunction in any docs/source/api/**/*.rst file:\n"
        f"  {missing}\n"
        "Add them to the appropriate page (handle docs are regenerated by "
        "`python docs/generate_handle_docs.py`)."
    )
