// The "floating" control-panel layout, on the docking library.
//
// Mounts a DockManager over the canvas area and seeds it with ONE panel: the
// control panel, as an unmergeable floating window in the top-right corner --
// matching the original FloatingPanel's default placement and feature set
// (drag, dock to either edge with canvas inset, resize from both edges,
// click-the-handle to minimize). Because it's an ordinary dock panel, it also
// composes with any other panels later added to the surface (e.g. GUI tabs
// dragged out of a nested dockable area).

import { Box } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import React from "react";
import { ViewerContext, ViewerContextContents } from "../ViewerContext";
import { htmlIconWrapper } from "../components/ComponentStyles.css";
import { DockMetricsContext, useDock } from "../dock/DockContext";
import { DockManager } from "../dock/DockManager";
import * as ops from "../dock/layoutOps";
import { PanelRegistry, emptyLayout } from "../dock/types";
import {
  CommandsButton,
  ConnectionStatus,
  ControlPanelContents,
  SettingsToggleIcon,
  ShareButton,
} from "./ControlPanel";
import GeneratedGuiContainer from "./Generated";
import { GuiDockContext } from "./GuiDockContext";
import { controlWidthPx } from "./controlWidth";

// Memoized so a torn-out tab's whole GUI tree doesn't re-render every time
// unrelated dock state changes (it only depends on its container uuid).
const MemoizedGeneratedGuiContainer = React.memo(GeneratedGuiContainer);

/** The control panel's panel id, fixed so sync code can find it. Its group /
 * window ids are generated by the layout ops; sync code locates them via
 * findPanelGroup + findGroupLocation. */
const CONTROL_PANEL_ID = "viser-control-panel";

// Match the original FloatingPanel's 15px boundary pad for initial placement.
const PANEL_PAD_PX = 15;

/** Where the control panel currently sits, reported up to App so the
 * notifications layer can offset itself clear of a left-docked panel. */
export interface ControlDockState {
  side: "left" | "right" | null;
  widthPx: number;
  expanded: boolean;
}

export function ControlPanelDockSurface({
  children,
  onDockStateChange,
}: {
  /** Center content (the canvas layers), inset when the panel is docked. */
  children: React.ReactNode;
  onDockStateChange?: (state: ControlDockState) => void;
}) {
  const viewer = React.useContext(ViewerContext)!;
  const controlWidthString = viewer.useGui(
    (state) => state.theme.control_width,
  );
  const widthPx = controlWidthPx(controlWidthString);
  const [showSettings, { toggle }] = useDisclosure(false);

  // GUI tab groups rendered inside the dock surface register here (via
  // GuiDockContext); the registry hook owns the lifetime of their tabs' panel
  // specs.
  const { guiPanels, registerTabGroup } = useGuiTabPanelRegistry(viewer);
  const guiDockValue = React.useMemo(
    () => ({ registerTabGroup }),
    [registerTabGroup],
  );

  const controlPanelSpec: PanelRegistry = React.useMemo(
    () => ({
      [CONTROL_PANEL_ID]: {
        id: CONTROL_PANEL_ID,
        title: "Control panel",
        unmergeable: true,
        unpadded: true,
        titleNode: (
          <>
            <ConnectionStatus />
            {/* Action icons: stop pointerdown so pressing them neither starts
            a panel drag nor registers as a minimize click on the header. */}
            <Box
              style={{ display: "flex", alignItems: "center" }}
              onPointerDown={(event) => event.stopPropagation()}
            >
              <CommandsButton />
              <ShareButton />
              <SettingsToggleIcon showSettings={showSettings} onToggle={toggle} />
            </Box>
          </>
        ),
        render: () => <ControlPanelContents showSettings={showSettings} />,
      },
    }),
    [showSettings, toggle],
  );
  const panels: PanelRegistry = React.useMemo(
    () => ({ ...guiPanels, ...controlPanelSpec }),
    [guiPanels, controlPanelSpec],
  );

  // The DockManager mounts IMMEDIATELY around the canvas (an empty layout is
  // just a passthrough container) -- mounting it later would reparent the
  // children and remount the R3F canvas, recreating the WebGL context. The
  // control panel window is then placed by ControlPanelDockSync once the
  // container width is measurable (top-right anchored).
  const initialLayout = React.useMemo(() => emptyLayout(), []);

  return (
    <div style={{ width: "100%", height: "100%", position: "relative" }}>
      <GuiDockContext.Provider value={guiDockValue}>
        <DockManager initialLayout={initialLayout} panels={panels}>
          {children}
          <ControlPanelDockSync
            widthPx={widthPx}
            onDockStateChange={onDockStateChange}
          />
        </DockManager>
      </GuiDockContext.Provider>
    </div>
  );
}


/** Owns the panel specs for GUI tab groups rendered inside the dock surface.
 * Each registered tab group gets a config-store subscription that keeps its
 * tabs' specs fresh (labels, icons, membership); when the SERVER removes the
 * tab group, its specs are dropped -- the DockManager's registry
 * reconciliation then removes the panels from wherever the user moved them.
 * Spec lifetime deliberately does NOT follow component mount state: a nested
 * tab group unmounts whenever an ancestor tab goes inactive, which must not
 * tear down its panels. */
function useGuiTabPanelRegistry(viewer: ViewerContextContents): {
  guiPanels: PanelRegistry;
  registerTabGroup: (uuid: string) => void;
} {
  const [guiPanels, setGuiPanels] = React.useState<PanelRegistry>({});
  // Per tab group: its config subscription, the panel ids it owns, and a
  // signature of the last-applied tab content (ids/labels/icons).
  const registry = React.useRef(
    new Map<
      string,
      { unsubscribe: () => void; panelIds: string[]; sig: string }
    >(),
  );

  const refreshTabGroup = React.useCallback(
    (uuid: string) => {
      const entry = registry.current.get(uuid);
      if (entry === undefined) return;
      const conf = viewer.useGuiConfig.get(uuid);
      const tabConf =
        conf !== undefined && conf.type === "GuiTabGroupMessage" ? conf : null;
      // The config store fires for ANY prop change on this uuid; only rebuild
      // the specs (new objects + icon elements, which re-renders every tab
      // panel) when the tab CONTENT actually changed.
      const sig =
        tabConf === null
          ? ""
          : JSON.stringify([
              tabConf.props._tab_container_ids,
              tabConf.props._tab_labels,
              tabConf.props._tab_icons_html,
            ]);
      if (tabConf !== null && sig === entry.sig) return;
      entry.sig = sig;
      const ownedBefore = new Set(entry.panelIds);
      if (tabConf === null) {
        entry.unsubscribe();
        registry.current.delete(uuid);
      } else {
        entry.panelIds = [...tabConf.props._tab_container_ids];
      }
      setGuiPanels((prev) => {
        const next: PanelRegistry = {};
        for (const [pid, spec] of Object.entries(prev)) {
          if (!ownedBefore.has(pid)) next[pid] = spec;
        }
        if (tabConf === null) return next;
        tabConf.props._tab_container_ids.forEach((cid: string, i: number) => {
          const iconHtml = tabConf.props._tab_icons_html[i];
          next[cid] = {
            id: cid,
            title: tabConf.props._tab_labels[i] ?? "Tab",
            icon:
              iconHtml == null ? undefined : (
                <div
                  className={htmlIconWrapper}
                  dangerouslySetInnerHTML={{ __html: iconHtml }}
                />
              ),
            unpadded: true,
            render: () => <MemoizedGeneratedGuiContainer containerUuid={cid} />,
          };
        });
        return next;
      });
    },
    [viewer],
  );
  const registerTabGroup = React.useCallback(
    (uuid: string) => {
      if (registry.current.has(uuid)) return;
      registry.current.set(uuid, {
        unsubscribe: viewer.useGuiConfig.subscribe(uuid, () =>
          refreshTabGroup(uuid),
        ),
        panelIds: [],
        // Sentinel that never matches a real signature, so the first refresh
        // always applies.
        sig: "\0unset",
      });
      refreshTabGroup(uuid);
    },
    [viewer, refreshTabGroup],
  );
  React.useEffect(() => {
    const reg = registry.current;
    return () => reg.forEach((entry) => entry.unsubscribe());
  }, []);
  return { guiPanels, registerTabGroup };
}

/** Non-rendering sync node inside the DockManager:
 * - applies server-driven control_width changes to the floating window;
 * - reports the panel's dock side/width/minimized state up to App (for the
 *   notifications offset);
 * - decorates the panel's DOM with the `floating-panel*` test ids and
 *   `data-dock-side` attribute that the e2e suite (and any user tooling built
 *   against the original FloatingPanel) targets. */
function ControlPanelDockSync({
  widthPx,
  onDockStateChange,
}: {
  widthPx: number;
  onDockStateChange?: (state: ControlDockState) => void;
}) {
  const dock = useDock();
  const metrics = React.useContext(DockMetricsContext);
  const markerRef = React.useRef<HTMLSpanElement>(null);

  // Narrow containers (small browser windows, split screens): shrink the
  // panel to fit with its padding rather than spilling past the right edge.
  // Shared by the initial placement and later server-driven width changes.
  const fitToContainer = React.useCallback((width: number) => {
    const containerW =
      markerRef.current
        ?.closest("[data-dock-root]")
        ?.getBoundingClientRect().width ?? 1280;
    return {
      containerW,
      width: Math.max(160, Math.min(width, containerW - 2 * PANEL_PAD_PX)),
    };
  }, []);

  // Initial placement: top-right corner, like the original FloatingPanel.
  // Runs once on mount (addFloatingPanel no-ops if the panel is already
  // placed, so a StrictMode double-run is harmless).
  React.useLayoutEffect(() => {
    const { containerW, width } = fitToContainer(widthPx);
    dock.api.apply(
      (layout) =>
        ops.addFloatingPanel(
          layout,
          CONTROL_PANEL_ID,
          Math.max(PANEL_PAD_PX, containerW - width - PANEL_PAD_PX),
          PANEL_PAD_PX,
          width,
        ).layout,
    );
    // Initial placement only; later width changes are applied below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Where is the control panel now?
  const controlGroupId = ops.findPanelGroup(dock.layout, CONTROL_PANEL_ID);
  const location =
    controlGroupId === null
      ? null
      : ops.findGroupLocation(dock.layout, controlGroupId);
  const side: "left" | "right" | "none" =
    location?.kind === "docked" ? location.edge : "none";
  const expanded =
    controlGroupId === null ||
    dock.groups[controlGroupId]?.collapsed !== true;
  // RENDERED width (expanded px + strip/divider chrome): the notifications
  // offset must clear everything the region actually draws, not just the
  // expanded columns' model width.
  const dockedWidth =
    location?.kind === "docked"
      ? metrics.reservedWidth[location.edge]
      : widthPx;

  // Server-driven width change: resize the floating window (a docked panel
  // keeps its region width -- the original applied prop width only as a base).
  const appliedWidth = React.useRef(widthPx);
  React.useEffect(() => {
    if (appliedWidth.current === widthPx) return;
    appliedWidth.current = widthPx;
    // Same narrow-container clamp as the initial placement, so a late
    // control_width update can't push the panel past the right edge.
    const { width } = fitToContainer(widthPx);
    dock.api.apply((layout) => {
      const gid = ops.findPanelGroup(layout, CONTROL_PANEL_ID);
      const loc = gid === null ? null : ops.findGroupLocation(layout, gid);
      return loc?.kind === "floating"
        ? ops.resizeWindow(layout, loc.windowId, width)
        : layout;
    });
  }, [widthPx, dock.api, fitToContainer]);

  // Report dock state up to App (notifications offset).
  React.useEffect(() => {
    onDockStateChange?.({
      side: side === "none" ? null : side,
      widthPx: dockedWidth,
      expanded,
    });
  }, [side, dockedWidth, expanded, onDockStateChange]);

  // Decorate the panel's current DOM element with the original FloatingPanel
  // test ids. The dock library's elements are generic (any panel can float or
  // dock); these attributes identify WHICH of them is the control panel, kept
  // in a side effect so the library stays viser-agnostic.
  const decorated = React.useRef<Element[]>([]);
  React.useEffect(() => {
    for (const el of decorated.current) {
      el.removeAttribute("data-testid");
      el.removeAttribute("data-dock-side");
    }
    decorated.current = [];
    const root = markerRef.current?.closest("[data-dock-root]");
    if (root == null || location === null) return;
    const tag = (el: Element | null, testid: string) => {
      if (el === null) return;
      el.setAttribute("data-testid", testid);
      decorated.current.push(el);
    };
    const panelEl =
      location.kind === "floating"
        ? root.querySelector(`[data-floating-window="${location.windowId}"]`)
        : location.kind === "docked"
          ? root.querySelector(`[data-dock-leaf="${location.nodeId}"]`)
          : null;
    tag(panelEl, "floating-panel");
    panelEl?.setAttribute("data-dock-side", side);
    // Expanded: the unmergeable header is the handle. Minimized to a strip:
    // there is no header -- the strip CELL is the drag/click handle, so the
    // testid follows it (the original FloatingPanel kept its handle testid
    // through minimize).
    tag(
      root.querySelector(`[data-dock-header="${controlGroupId}"]`) ??
        root.querySelector(
          `[data-dock-group="${controlGroupId}"][data-dock-collapsed]`,
        ),
      "floating-panel-handle",
    );
    if (location.kind === "floating" && panelEl !== null) {
      tag(
        panelEl.querySelector('[data-dock-resize="left"]'),
        "floating-panel-resize-left",
      );
      tag(
        panelEl.querySelector('[data-dock-resize="right"]'),
        "floating-panel-resize-right",
      );
    }
    // Re-decorate only when the panel's element identity can actually change
    // (layout restructures recreate DOM nodes) -- not on every render, which
    // would churn DOM attributes per resize frame.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dock.layout, side, controlGroupId]);

  return <span ref={markerRef} style={{ display: "none" }} />;
}
