/** Single source of truth for the Inter font binary.
 *
 * Both the DOM (via the @font-face rule injected below) and troika 3D labels
 * (LabelUtils.ts) reference this one import. Registering the @font-face from
 * JS instead of index.css means the font is inlined exactly once in the
 * single-file production build; a CSS url() and a JS import would each get
 * their own base64 copy.
 *
 * The asset is generated by scripts/optimize_font.py; see that script for
 * what was trimmed relative to the original Inter release.
 */
import interFontUrl from "./assets/InterVariable-optimized.ttf";

if (typeof document !== "undefined") {
  const style = document.createElement("style");
  // Weight range matches the optimized font's `wght` axis. No italic face is
  // declared, so browsers synthesize oblique for italic text.
  style.textContent = `@font-face {
  font-family: "Inter";
  src: url("${interFontUrl}") format("truetype");
  font-weight: 400 700;
  font-style: normal;
}`;
  document.head.appendChild(style);
}

export { interFontUrl };
