name: Setup E2E environment
description: Install Python, Node.js, dependencies, Playwright, and build the viser client.

inputs:
  python-version:
    description: Python version to install.
    required: false
    default: "3.12"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python dependencies
      shell: bash
      run: uv sync --extra dev

    - name: Install Playwright browsers
      shell: bash
      run: uv run playwright install chromium --with-deps

    - name: Build viser client
      shell: bash
      run: |
        cd src/viser/client
        npm install
        npm run build
